[core]
workspace_path = "."
base_branch = "main"

[jira]
base_url = "https://<your_company>.atlassian.net"
username = "<username>@gmail.com"
api_token = "<jira_token>"

[github]
username = "<username>"
api_token = "github_token"
repo_full_name = "owner/repo"
